services:

  mongo_config_a:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongo_config_a
    restart: always
    networks:
      app-network:
    volumes:
      - mongo_config_a_db:/data/db
      - mongo_config_a_configdb:/data/configdb
    command: ["--configsvr", "--replSet", "config", "--bind_ip_all", "--port", "27019"]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27019"]
      interval: 5s
      start_period: 10s

  mongo_shard1_a:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongo_shard1_a
    restart: always
    networks:
      app-network:
    volumes:
      - mongo_shard1_a_db:/data/db
      - mongo_shard1_a_configdb:/data/configdb
    command: ["--shardsvr", "--replSet", "shard1", "--bind_ip_all", "--port", "27018"]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27018"]
      interval: 5s
      start_period: 10s
  mongo_shard1_b:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongo_shard1_b
    restart: always
    networks:
      app-network:
    volumes:
      - mongo_shard1_b_db:/data/db
      - mongo_shard1_b_configdb:/data/configdb
    command: ["--shardsvr", "--replSet", "shard1", "--bind_ip_all", "--port", "27018"]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27018"]
      interval: 5s
      start_period: 10s
  mongo_shard1_c:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongo_shard1_c
    restart: always
    networks:
      app-network:
    volumes:
      - mongo_shard1_c_db:/data/db
      - mongo_shard1_c_configdb:/data/configdb
    command: ["--shardsvr", "--replSet", "shard1", "--bind_ip_all", "--port", "27018"]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27018"]
      interval: 5s
      start_period: 10s

  mongo_shard2_a:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongo_shard2_a
    restart: always
    networks:
      app-network:
    volumes:
      - mongo_shard2_a_db:/data/db
      - mongo_shard2_a_configdb:/data/configdb
    command: ["--shardsvr", "--replSet", "shard2", "--bind_ip_all", "--port", "27018"]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27018"]
      interval: 5s
      start_period: 10s
  mongo_shard2_b:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongo_shard2_b
    restart: always
    networks:
      app-network:
    volumes:
      - mongo_shard2_b_db:/data/db
      - mongo_shard2_b_configdb:/data/configdb
    command: ["--shardsvr", "--replSet", "shard2", "--bind_ip_all", "--port", "27018"]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27018"]
      interval: 5s
      start_period: 10s
  mongo_shard2_c:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongo_shard2_c
    restart: always
    networks:
      app-network:
    volumes:
      - mongo_shard2_c_db:/data/db
      - mongo_shard2_c_configdb:/data/configdb
    command: ["--shardsvr", "--replSet", "shard2", "--bind_ip_all", "--port", "27018"]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27018"]
      interval: 5s
      start_period: 10s
  
  mongo_router1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongo_router1
    restart: always
    networks:
      app-network:
    command: ["mongos", "--configdb", "config/mongo_config_a:27019", "--bind_ip_all", "--port", "27017"]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')", "--port", "27017"]
      interval: 5s
      start_period: 10s

  redis_a:
    image: "redis:latest"
    container_name: redis_a
    networks:
      app-network:
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
  
  pymongo_api:
    container_name: pymongo_api
    build: 
      context: ../api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    ports:
      - 8080:8080
    networks:
      app-network:
    environment:
      MONGODB_URL: "mongodb://mongo_router1"
      MONGODB_DATABASE_NAME: "somedb"
      REDIS_URL: "redis://redis_a:6379"
    depends_on:
      mongo_router1:
        condition: service_healthy
      redis_a:
        condition: service_healthy

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16

volumes:
  mongo_config_a_db:
  mongo_config_a_configdb:
  mongo_shard1_a_db:
  mongo_shard1_a_configdb:
  mongo_shard1_b_db:
  mongo_shard1_b_configdb:
  mongo_shard1_c_db:
  mongo_shard1_c_configdb:
  mongo_shard2_a_db:
  mongo_shard2_a_configdb:
  mongo_shard2_b_db:
  mongo_shard2_b_configdb:
  mongo_shard2_c_db:
  mongo_shard2_c_configdb: